apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sgxlkl-device-plugin
  namespace: kube-system
  labels:
    app: sgxlkl-device-plugin
spec:
  selector:
    matchLabels:
      app: sgxlkl-device-plugin
  template:
    metadata:
      labels:
        app: sgxlkl-device-plugin
    spec:
      containers:
      - name: sgxlkl-device-plugin
        image: "vtikoo/sgxlkl-device-plugin:0.1"
        command: ["/usr/local/bin/sgxlkl-device-plugin"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: opt-sgxlkl
          mountPath: /opt/sgxlkl
        securityContext:
          privileged: true
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
      - name: opt-sgxlkl
        hostPath:
          path: /opt/sgxlkl
